# config/database.yml
development:
  adapter: mysql
  database: outline_os_development
  username: root
  password: root
  host: localhost

production:
  adapter: mysql
  database: outline_os_production
  username: root
  password: root
  host: localhost

test:
  adapter: mysql
  database: outline_os_test
  username: root
  password: root
  host: localhost

